name: slrgnn
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.9
  - pyg=2.0.4
  - networkx=3.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch_geometric
  - tqdm=4.66
  - numpy
