name: slrgnn
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.9
  - pip=24.0
  - networkx=3.1
  - pytorch
  - torchvision
  - torchaudio
  - tqdm=4.66
  - numpy
  - pyg
  - pip:
    - scikit-learn
    - scipy